# Generated by Django 3.0.2 on 2020-06-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('qualification', models.CharField(choices=[('Under Graduate', 'Under Graduate'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=250, null=True)),
                ('experiance', models.CharField(choices=[('Fresher', 'Fresher'), ('1-3', '1-3'), ('4-6', '4-6'), ('6-10', '6-10'), ('More than 10', 'More than 10')], max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('companies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Companies')),
            ],
        ),
    ]
