# Generated by Django 3.0.2 on 2020-06-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200605_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='companies',
        ),
        migrations.AddField(
            model_name='application',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Jobs'),
        ),
    ]
