# Generated by Django 3.0.2 on 2020-06-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_applicant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Applicant'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='companies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Companies'),
        ),
    ]
