# Generated by Django 3.0.2 on 2020-06-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200626_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='applied',
        ),
    ]
